#!/usr/bin/env python3
# SPDX-License-Identifier: Apache-2.0
# Copyright 2026 Vinod Dhiman and UAGT contributors
"""Reverse-coverage index: from each SOURCE framework element back to the Master Controls.

Proves that every inventoried element of the three anchor frameworks (ISO/IEC 42001 Annex A,
NIST AI RMF subcategories, EU AI Act governance articles) maps to at least one Master Control
— and flags any **orphan** (an inventory element no control maps to). Also lists refs that
controls use but that are not in the inventory (e.g. ISO main-body clauses), as a hygiene
check. Output: docs/reverse-coverage.md.

Usage:
  python scripts/build_reverse_coverage.py            # write docs/reverse-coverage.md
  python scripts/build_reverse_coverage.py --check    # validate only, no write (CI)
"""
from __future__ import annotations

import argparse
import sys

from build_tables import FRAMEWORK_LABELS, ROOT, load_controls, load_yaml

INVENTORY_PATH = ROOT / "data" / "source-inventory.yaml"
OUT = ROOT / "docs" / "reverse-coverage.md"
ANCHORS = ["ISO-IEC-42001", "NIST-AI-RMF", "EU-AI-ACT"]


def build(controls):
    inv = load_yaml(INVENTORY_PATH)
    # ref -> [(control_id, relationship)], per framework (only mappings that carry a ref)
    used: dict[str, dict[str, list]] = {fw: {} for fw in ANCHORS}
    for c in controls:
        for m in c.get("mappings", []):
            fw, ref = m["framework"], m.get("ref")
            if fw in used and ref:
                used[fw].setdefault(ref, []).append((c["id"], m["relationship"]))

    lines = ["# UAGT Reverse-Coverage Index", ""]
    lines.append("> Generated by `scripts/build_reverse_coverage.py` — do not edit by hand.")
    lines.append(
        "> From each source element back to the Master Controls that map to it. **Orphan** = "
        "an inventoried element that no Master Control covers (a forward gap in the crosswalk)."
    )
    lines.append("")

    summary = []
    orphan_total = 0
    for fw in ANCHORS:
        elements = inv[fw]
        inv_refs = {e["ref"] for e in elements}
        covered = sum(1 for e in elements if used[fw].get(e["ref"]))
        orphans = len(elements) - covered
        orphan_total += orphans
        summary.append((fw, covered, len(elements), orphans))

        lines.append(f"## {FRAMEWORK_LABELS[fw]} — {covered}/{len(elements)} elements covered")
        lines.append("")
        lines.append("| Source element | Mapped Master Controls |")
        lines.append("| --- | --- |")
        for e in elements:
            hits = used[fw].get(e["ref"])
            if hits:
                cell = ", ".join(f"{cid} ({rel})" for cid, rel in sorted(hits))
            else:
                cell = "— **orphan (no Master Control)**"
            lines.append(f"| `{e['ref']}` {e['title']} | {cell} |")
        lines.append("")

        extra = sorted(r for r in used[fw] if r not in inv_refs)
        if extra:
            lines.append(f"**Referenced outside the inventory** (e.g. main-body clauses): "
                         + ", ".join(f"`{r}`" for r in extra))
            lines.append("")

    head = ["## Summary", "", "| Framework | covered | total | orphans |",
            "| --- | ---: | ---: | ---: |"]
    for fw, cov, tot, orp in summary:
        head.append(f"| {FRAMEWORK_LABELS[fw]} | {cov} | {tot} | {orp} |")
    head.append("")
    # insert summary right after the intro (before first framework section)
    intro_end = lines.index("") + 1 if "" in lines else len(lines)
    # find the blank line just before the first "## " framework heading
    first_h2 = next(i for i, l in enumerate(lines) if l.startswith("## "))
    lines = lines[:first_h2] + head + lines[first_h2:]

    return "\n".join(lines) + "\n", orphan_total


def main() -> int:
    ap = argparse.ArgumentParser(description="Build the reverse-coverage index.")
    ap.add_argument("--check", action="store_true", help="validate only; no output")
    args = ap.parse_args()

    controls = load_controls()
    md, orphans = build(controls)
    print(f"reverse-coverage OK — {orphans} orphan element(s) across the three anchor inventories")
    if args.check:
        return 0
    OUT.write_text(md, encoding="utf-8")
    print(f"wrote {OUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
